# Generated by Django 4.2.2 on 2023-06-24 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("serving", models.CharField(max_length=200)),
                ("calories", models.PositiveIntegerField()),
                ("protein", models.PositiveIntegerField(default=0)),
                ("carbohydrate", models.PositiveIntegerField(default=0)),
                ("fat", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Vitamin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="food_calori_name_ab8a70_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Mineral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="food_calori_name_d9a74e_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="FoodVitamin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveIntegerField()),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_calorie.food",
                    ),
                ),
                (
                    "vitamin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_calorie.vitamin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodMineral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveIntegerField()),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_calorie.food",
                    ),
                ),
                (
                    "mineral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_calorie.mineral",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="food",
            name="minerals",
            field=models.ManyToManyField(
                through="food_calorie.FoodMineral", to="food_calorie.mineral"
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="vitamins",
            field=models.ManyToManyField(
                through="food_calorie.FoodVitamin", to="food_calorie.vitamin"
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(fields=["name"], name="food_calori_name_c02262_idx"),
        ),
    ]
