# Generated by Django 4.2.2 on 2023-06-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_calorie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="carbohydrate",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="food",
            name="fat",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="food",
            name="protein",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="foodmineral",
            name="value",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name="foodvitamin",
            name="value",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
